name: Deploy static site to Azure Web App - RahaApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B6B35ED3016C4D3A9C8913038121F00A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_20D9AA6F78AD4470BB484057CC522038 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A27447A96B51494D94680A2CC410CC9B }}

      - name: Deploy static content to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'RahaApp' # your web app name
          slot-name: 'Production'
          package: . # deploys current folder (static files)

          
